version: '3.8'

services:
  devtools:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${ENVIRONMENT:-production}-devtools
    restart: unless-stopped
    ports:
      - ${PORT:-80}:80
    environment:
      - NODE_ENV=production
    networks:
      - devtools-network

networks:
  devtools-network:
    driver: bridge
